#! /bin/bash

set -e
set -o pipefail

# Déploiement des .pp vers la machine de destination
DEST=vagrant@192.168.56.10
DEST_DIR=/etc/puppetlabs/code/environments/production/manifests/

# Validation de la syntaxe des fichiers
#bash

shellcheck scripts/*

# manifest puppet
/opt/puppetlabs/bin/puppet parser validate modules/init*.pp
/opt/puppetlabs/bin/puppet parser validate manifests/*.pp

rsync -a --delete modules/ $DEST:$DEST_DIR
rsync -a --delete manifests/ $DEST:$DEST_DIR
